server:
  port: ${PORT:8087}

spring:
  application:
    name: ms-bills

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  security:
    oauth2:
      client:
        provider:
          keycloak-provider:
            issuer-uri: http://localhost:8080/realms/parcial-suarez-victoria
        registration:
          ms-bills:
            provider: keycloak-provider
            client-id: api-bills
            client-secret: AG6XFi5hRIvqKJfqFQcEVttOMb2KqZ8Z
            scope:
              - openid
            authorization-grant-type: client_credentials
            redirect-uri: 'http://localhost:8086/login/oauth2/code/keycloak'